name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow the bot to write to the repository
      pages: write     # Allow the bot to push to GitHub Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "TihoAska"
          git config --global user.email "tihomirascic18@gmail.com"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Specify the version of Node.js

      - name: Clean npm cache and install dependencies
        run: |
          rm -rf node_modules
          npm install

      - name: Inject backendUrl
        run: |
          # Ensure the directory exists
          mkdir -p src/environments
          # Create a custom prod environment file with the backend URL secret
          echo "export const environment = { production: true, backendUrl: '${{ secrets.BACKEND_URL }}' };" > src/environments/environment.prod.ts

      - name: Verify environment.prod.ts file
        run: cat src/environments/environment.prod.ts

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli 

      - name: Build Angular app
        run: ng build --configuration=production  # Build the app in production mode

      - name: Deploy to GitHub Pages
        run: ng deploy